// Regenerates src/allowed.js from the system dictionary.
//
//   node tools/build-allowed.mjs
//
// The generated file is committed, so you only need to run this if you want to
// widen the set of words a player is permitted to guess. src/answers.js is NOT
// generated — it is hand-curated, and words.js unions it in at runtime.
//
// Source: /usr/share/dict/web2 (Webster's Second, shipped with macOS and most
// BSDs; `words` is a symlink to it). It has no inflected forms at all, so
// "trees" and "bakes" are missing while "tree" and "bake" are present. We add
// <four-letter word> + "s" to cover the plural/third-person case, which is by
// far the most common thing a player types and has rejected on them.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const DICT = process.env.BEEDLE_DICT ?? '/usr/share/dict/web2';
const OUT = fileURLToPath(new URL('../src/allowed.js', import.meta.url));

const lines = readFileSync(DICT, 'utf8').split('\n');
const words = new Set();

for (const line of lines) {
  const w = line.trim();
  if (/^[a-z]{5}$/.test(w)) words.add(w);
  else if (/^[a-z]{4}$/.test(w)) words.add(`${w}s`);
}

const sorted = [...words].sort();
const body = sorted.map((w) => `'${w}'`).join(',');

writeFileSync(
  OUT,
  // JSON.stringify, not interpolation: DICT comes from the environment, and
  // codegen is the wrong place to learn that habit.
  `// GENERATED by tools/build-allowed.mjs from ${JSON.stringify(DICT)} — do not edit by hand.\n` +
    `// ${sorted.length} words. Answers are unioned in separately by words.js.\n` +
    `export const ALLOWED = [${body}];\n`,
);

console.log(`wrote ${sorted.length} words to ${OUT}`);
